# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aj6c_c7jronC0okU72DRzNpDBMekkObK
"""

#Escoger un conjuto de datos de mi interes

import pandas as pd
from google.colab import files
uploaded = files.upload()

print ( "CONJUNTO DE DATOS ACERCA DE PELICULAS Y SERIES DE TELEVISION DISPONIBLES EN NETFLIX")
df = pd.read_csv('/content/netflix_titles.csv')

df.head()

print ( "EXPLORACION DE DATOS")
print ("VISUALIZACION DE LAS INFORMACION")
df.head()

print (("CANTIDAD DE FILAS:") , df.shape[0])
print (("CANTIDAD DE COLUMNAS:") , df.shape[1])
print (("INFORMACION GENERAL") , df.info())
print(("EXPLORACION DE DATOS NULOS"), df.isnull())
porcentaje_nulos = (df.isnull().sum() / len(df) * 100).round(2)

porcentaje_nulos

print ("EXPLORACION DE DATOS NULOS")
df.isnull().sum()

porcentaje_nulos = (df.isnull().sum() / len(df) * 100).round(2)

porcentaje_nulos

df[df['rating'].str.contains('min', na=False)][['title', 'rating', 'duration']]
df.loc[df['rating'].str.contains('min', na=False), 'rating'] = 'Unknown'

print ("EXPLORACION DE DATOS DUPLICADOS")
print("CANTIDAD DE DATOS DUPLICADOS:", df.duplicated().sum())

#REMPLAZAR VALORES NULOS
print("VALORES NULOS ")
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Unknown')
df.isnull().sum()

print ("TRANSFORMACION DE COLUMNAS Y CREACION DE VARIABLES")

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year
df[['title', 'date_added', 'year_added']].head()

print ("AGRUPACIONES CON GROUPBY")
print ("PELICULAS Y SERIES DISPONIBLES")
contenido_tipo = (
    df.groupby('type')
      .size()
      .reset_index(name='cantidad')
)

contenido_tipo

print ("CONTENIDO AGREGADO POR AÑO")
contenido_año = (
    df.groupby('year_added')
      .size()
      .reset_index(name='cantidad')
      .sort_values('year_added')
)

contenido_año

print ("CONTENIDO AGREGADO POR CLASIFICACION")
contenido_rating = (
    df.groupby('rating')
      .size()
      .reset_index(name='cantidad')
      .sort_values('cantidad', ascending=False)
)

contenido_rating

print ("¿HAY MAS PELICULAS O SERIES DE TELEVISION EN NETFLIX?")

contenido_tipo = df.groupby('type').size().reset_index(name='cantidad')

contenido_tipo
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(contenido_tipo['type'], contenido_tipo['cantidad'])

plt.title('Cantidad de películas y series en Netflix')
plt.xlabel('Tipo de contenido')
plt.ylabel('Cantidad de títulos')

plt.show()

"""**INTERPRETACION:** El catálogo analizado de Netflix tiene una mayor cantidad de películas que de series. Se identificaron 6.131 películas, mientras que las series de televisión representan 2.676 títulos. Esto significa que las películas constituyen aproximadamente el 70% del contenido analizado, mientras que las series representan cerca del 30%."""

print ("¿COMO HA VARIADO LA CANTIDAD DE CONTENIDO AGREGANDO A NETFLIX A TRAVES DE LOS AÑOS?")
contenido_año = (
    df.groupby('year_added')
      .size()
      .reset_index(name='cantidad')
      .sort_values('year_added')
)

contenido_año

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.plot(
    contenido_año['year_added'],
    contenido_año['cantidad'],
    marker='o'
)

plt.title('Cantidad de contenido agregado a Netflix por año')
plt.xlabel('Año')
plt.ylabel('Cantidad de títulos')

plt.grid(True)
plt.show()

"""Interpretación: La cantidad de contenido agregado a Netflix aumentó durante los primeros años del período analizado y alcanzó su punto más alto en 2019, después se observa una disminución en los años siguientes. Esto indica que la incorporación de nuevos títulos no fue constante, sino que tuvo un período de crecimiento importante antes de reducirse."""

print ("CUALES SON LOS PAISES QUE TIENEN MAYOR CANTIDAD DE CONTENIDO EN NETFLIX?")
contenido_pais = (
    df.groupby('country')
    .size()
    .reset_index(name='cantidad')
    .sort_values('cantidad', ascending=False)
)

# Excluir los registros sin país identificado
contenido_pais = contenido_pais[contenido_pais['country'] != 'Unknown']

top_10_paises = contenido_pais.head(10)
plt.figure(figsize=(10,6))

plt.bar(
    top_10_paises['country'],
    top_10_paises['cantidad']
)

plt.title('Top 10 países con mayor cantidad de contenido en Netflix')
plt.xlabel('País')
plt.ylabel('Cantidad de títulos')

plt.xticks(rotation=45, ha='right')

plt.show()

"""**Interpretación:** Estados Unidos es el país con mayor cantidad de contenido en el conjunto de datos de Netflix, seguido por India y Reino Unido. Los demás países del Top 10 presentan una cantidad considerablemente menor de títulos."""

print ("¿Cuales son los generos o categorias de contenido mas populares en Netflix?")
df_generos = df.copy()
df_generos['listed_in'] = df_generos['listed_in'].str.split(', ')
df_generos = df_generos.explode('listed_in')
contenido_genero = (
    df_generos.groupby('listed_in')
    .size()
    .reset_index(name='cantidad')
    .sort_values('cantidad', ascending=False)
)

contenido_genero.head(10)
top_10_generos = contenido_genero.head(10)

plt.figure(figsize=(10,6))

plt.bar(
    top_10_generos['listed_in'],
    top_10_generos['cantidad']
)

plt.title('Top 10 categorías de contenido más frecuentes en Netflix')
plt.xlabel('Categoría')
plt.ylabel('Cantidad de títulos')

plt.xticks(rotation=45, ha='right')

plt.show()

"""**Interpretación: **Las categorías con mayor presencia en el catálogo analizado son International Movies y Dramas, seguidas por Comedies e International TV Shows. También tienen una presencia importante los documentales y las producciones de acción y aventura."""

print ("¿Cuales son las clasificaciones de edad mas comunes entre las peliculas y series de Netflix?")
contenido_rating = (
    df.groupby('rating')
      .size()
      .reset_index(name='cantidad')
      .sort_values('cantidad', ascending=False)
)

contenido_rating
rating_conocido = contenido_rating[
    contenido_rating['rating'] != 'Unknown'
]

plt.figure(figsize=(10,6))

plt.bar(
    rating_conocido['rating'],
    rating_conocido['cantidad']
)

plt.title('Distribución de las clasificaciones de edad en Netflix')
plt.xlabel('Clasificación de edad')
plt.ylabel('Cantidad de títulos')

plt.xticks(rotation=45)

plt.show()

"""**Interpretación**: La clasificación más frecuente en el conjunto de datos es TV-MA, con más de 3.000 títulos. Le sigue TV-14, con más de 2.000 títulos. Después aparecen TV-PG y R, aunque con una cantidad considerablemente menor. Esto indica que una parte importante del catálogo analizado corresponde a contenidos dirigidos principalmente a adolescentes mayores y adultos

**CONCLUSIONES**

1. El catálogo analizado tiene una mayor presencia de películas que de series.
De los 8.807 títulos analizados, 6.131 son películas y 2.676 son series, por lo que las películas representan aproximadamente el 70% del conjunto de datos. Esto muestra que, dentro de la base analizada, la oferta de películas tiene un peso considerablemente mayor que la de series.

2. El contenido del catálogo presenta una fuerte diversidad geográfica y temática.
El análisis por países muestra que Estados Unidos aparece asociado con la mayor cantidad de títulos, seguido por India y Reino Unido. Al mismo tiempo, las categorías más frecuentes incluyen International Movies, Dramas y Comedies. Esto indica que el catálogo analizado combina contenido de diferentes países y géneros, en lugar de concentrarse en una sola categoría de entretenimiento.

3. Las clasificaciones de edad muestran una concentración en contenidos dirigidos a públicos adolescentes y adultos. La clasificación TV-MA es la más frecuente, seguida por TV-14, mientras que otras clasificaciones presentan cantidades menores. Este patrón indica que una parte importante del contenido analizado está clasificada para públicos de mayor edad, por lo que el catálogo no está compuesto principalmente por contenidos dirigidos a niños o a todas las edades.
"""